name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Create Doxygen Documentation 🔧
      run: |
         sudo apt-get install python3 python3-setuptools python-pip -y
         sudo apt-get install gcc libpq-dev -y
         sudo apt-get install python-dev  python-pip -y
         sudo apt-get install python3-dev python3-pip python3-venv python3-wheel -y
         pip3 install wheel pylode
         mkdir docs
         cd docs
         pylode -i ../ogiogham.owl
    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         BRANCH: gh-pages
         FOLDER: docs/
